### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by maplerichie** [woosignal/wp-json-api-flutter#1]
```
/wp-json/wpapp/auth/v1/nonce
```
The login request send to this path, but the other library which able to login using path below
```
/wp-json/wp/v2/
```

WordPress 5.4.1
WooCommerce 4.1.1
woosignal: ^1.0.8
wp_json_api: ^0.1.2

**Comment by agordn52** [comment]
Do you have the latest version of the plugin installed?
https://woosignal.com/plugins/wordpress/wp-json-api 

To login you only need to call the following methods in your code.

``` dart
import 'package:wp_json_api/wp_json_api.dart';
...

void main() {

WPJsonAPI.instance.initWith(baseUrl: "https://mysite.com");

...
```

``` dart
WPUserLoginResponse wpUserLoginResponse = await WPJsonAPI.instance
          .api((request) => request.wpLogin(
            email: "email",
            password: "password"
          ));


print(wpUserLoginResponse);
```

If you're using a WooSignal template you won't need to do any of the above.

**Comment by maplerichie** [comment]
So the path `/wpapp/auth/v1/nonce` is not WordPress API?

**Comment by agordn52** [comment]
The `/wpapp/auth/v1/nonce` endpoint is apart of the https://woosignal.com/plugins/wordpress/wp-json-api WordPress plugin.

You'll need to have it installed on your store first to access the APIs the plugin includes.
