### ISSUE TITLE
Result status and message null?

### ISSUE THREAD

**Issue by moarief** [woosignal/wp-json-api-flutter#2]
Hi,

I am using the plugin, which is great by the way, but i can't get the status code or the error message from the api callbacks?

Would like to implement some visual feedback to users depending on the error message or status code..

Using the WPUserLoginResponse method, and it works like a charme:

    WPUserLoginResponse wpUserLoginResponse = await WPJsonAPI.instance.api(
      (request) {
        return request.wpLogin(
            username: username,
            password: password,
            authType: WPAuthType.WpUsername);
      },
    );

    if (wpUserLoginResponse != null) {
      userTokenId = wpUserLoginResponse.data.userToken;
      print(wpUserLoginResponse.message); // not working??
      getUser(userTokenId, context);
    } else {
      print("invalid login details");
      print(wpUserLoginResponse.message); // not working??
      errorMessage = "invalid login details";
      loginState = LoginState.signedout;
      notifyListeners();
    }

I keep getting this error:

```
E/flutter ( 9788): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'message' was called on null.
E/flutter ( 9788): Receiver: null
E/flutter ( 9788): Tried calling: message
E/flutter ( 9788): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
E/flutter ( 9788): #1      Wordpress.login 
package:mindmover/providers/wordpress.dart:45
E/flutter ( 9788): <asynchronous suspension>
E/flutter ( 9788): #2      _LoginPageState.build.<anonymous closure> 
```

**Comment by moarief** [comment]
Ah I see,

Only status code: 200 will show anything else not. But would be great to have the other options, for more precise error handling.

**Comment by agordn52** [comment]
Hi, 

Thanks for your feedback on this, it's something we can certainly look into for the next version.

**Comment by moarief** [comment]
Another question if you don't mind?

I am using Bloc pattern for state management and when i use the method WPUserInfoResponse to access user data to set currentuser, i keep getting null after i login and try to access the currentuser on userpage?

Keep getting error - 

   The following NoSuchMethodError was thrown building UserPage(dirty, dependencies: 
   [InheritedProvider<Wordpress>], state: _UserPageState#df273):
   The getter 'username' was called on null.
   Receiver: null
   Tried calling: username
   The relevant error-causing widget was:
   UserPage file:///F:/Flutter/mindmover/lib/providers/wordpress.dart:82:31


Wordpress changenotifier:
```
getUser(String userTokenId, context) async {
    WPUserInfo.WPUserInfoResponse wpUserInfoResponse =
        await WPJsonAPI.instance.api(
      (request) {
        notifyListeners();
        return request.wpGetUserInfo(userTokenId);
      },
    );

    if (wpUserInfoResponse != null) {
      print(wpUserInfoResponse.data.username);
      currentuser = wpUserInfoResponse.data;
      notifyListeners();
      onValidUser(currentuser, context);
    } else {
      wpUserInfoResponse.message.toString();
      errorMessage = 2;
      print("something went wrong");
      //errorMessage = "Something whent wrong";
    }
  }
```
MyApp class:
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<Player>.value(
          value: Player(),
        ),
        ChangeNotifierProvider<Wordpress>(
          create: (_) { return Wordpress(); },
          child: AppBottomNavigationBar(),
        )
      ],
```
User page: 

```
@override
  Widget build(BuildContext context) {
  Wordpress wordpress = Provider.of(context);
  
    return Scaffold(
      appBar: AppBar(
        actions: <Widget>[
          FlatButton(
            onPressed: () => {
              Navigator.pushReplacement(
                context,
                MaterialPageRoute(
                  builder: (_) => AppBottomNavigationBar(),
                ),
              ),
            },
            child: Icon(Icons.add_circle_outline),
          ),
        ],
      ),
      body: Container(
        child: Column(
          children: <Widget>[
            FlatButton(
              onPressed: null,
              child: Text(wordpress.currentUserModel.username),
            ),
          ],
        ),
      ),
    );
}
```

**Comment by agordn52** [comment]
Hi, @MoActive in the latest release (`v0.1.4+`) you can catch exceptions like the following example below:
``` dart
try {
    WPUserLoginResponse wpUserLoginResponse = await WPJsonAPI.instance
       .api((request) => request.wpLogin(
       email: email,
      password: password
   ));
} on Exception catch (e) {
    print(e);
} 
```

Check the method documentation to see all the different exceptions you can catch.
Also, you should have the latest version of WP JSON API `v2.0.0+` plugin installed on WordPress from WooSignal.

Hope that helps 👍
