### ISSUE TITLE
how to additional fields to register user

### ISSUE THREAD

**Issue by MichaelSowah** [woosignal/wp-json-api-flutter#3]
How do I add additional fields such as user role, phone number, etc to register a user?

**Comment by agordn52** [comment]
Hi @MichaelSowah, the API supports registration with an email, username and password. 
```dart
WPUserRegisterResponse wpUserRegisterResponse = await WPJsonAPI.instance
      .api((request) => request.wpRegister(
         email: email,
         password: password,
         username: username
      ));
```
Once they are logged in, you could then call the API to update the user's phone number. 
If it's the 'billing phone number' field, you could use the below API method or `shippingPhone` for the 'shipping phone number'.

``` dart
WCCustomerUpdatedResponse wcCustomerUpdatedResponse = await WPJsonAPI.instance
        .api((request) => request.wcUpdateCustomerInfo(
            userToken,
            billingPhone: billingPhone
        ));
```

Re. the role, the API currently doesn't support that.
We can add it to the backlog of things to do, might have a quick turnaround on this for you.

**Comment by MichaelSowah** [comment]
Thanks, I would really appreciate that especially the ability to pass the role of the user eg: customer, admin, etc.
At least an optional parameter/field for the dev to pass the user role will be very great for me please as I have different users with different roles creating accounts on my app...how possible is this and what's likely the timeline for adding the role parameter/field?

**Comment by agordn52** [comment]
Hi @MichaelSowah, [v3.1.2](https://github.com/woosignal/wp-json-api-flutter/releases/tag/v3.1.2) supports the ability to add/remove roles.

#### Add a new role to a user
``` dart
WPUserAddRoleResponse wpUserAddRoleResponse = await WPJsonAPI.instance
        .api((request) => request.wpUserAddRole(
            userToken,
            role: "customer" // e.g. customer, subscriber
        ));
```
---
#### Remove role from a user
``` dart
WPUserRemoveRoleResponse wpUserRemoveRoleResponse = await WPJsonAPI.instance
        .api((request) => request.wpUserRemoveRole(
            userToken,
            role: "customer" // e.g. customer, subscriber
        ));
```

You'll need to update your WordPress plugin [WP JSON API](https://woosignal.com/plugins/wordpress/wp-json-api) to `v3.1.0`.

**Comment by MichaelSowah** [comment]
great, I updated my plugin

**Comment by MichaelSowah** [comment]
How do I persist nonce with the single sign-on?
