### ISSUE TITLE
Question - Support for Posts API

### ISSUE THREAD

**Issue by korzonkiee** [woosignal/wp-json-api-flutter#4]
Hey!

First of all, I wanted to thank the maintainers for this package, it looks really promising!

Do you plan to add support for the [Word Press Posts API](https://developer.wordpress.org/rest-api/reference/posts/)?

**Comment by agordn52** [comment]
Hey,

Thanks for the comment, means a lot!

Re. Posts
Yeah, I think that would be a nice addition to the library. 
In the next release we'll get this added 👍
